### PR TITLE
Add Pandoc-style YAML metadata header

### PR DESCRIPTION
**Pull request by rgieseke**
See https://pandoc.org/MANUAL.html#metadata-blocks

### CODE REVIEW

**Comment by perrette** [comment]
I wonder whether we could have this in the config file, i.e. whether this would make sense to have all configuration/metadata in one place. That would be an argument to have the config file in yml format. That is not necessarily a good idea, I am just thinking loud.

**Comment by rgieseke** [comment]
Or to have everything as YAML in the Markdown header ... duplication as it is in every copy/rendered country version but would lead to a self contained template (thinking out loud as well :-)

```yaml

---
title:  'This is the title: it contains a colon'
author:
- name: Author One
  affiliation: University of Somewhere
- name: Author Two
  affiliation: University of Nowhere
keywords: [nothing, nothingness]
abstract: |
  This is the abstract.
  It consists of two paragraphs.
indicator: Drought
topics: 
    - Extreme events
    - Water
study-type: future-projections
- ranking-files: 
  - land-abs-temp: 
      - direction: desc
  - land-abs-time:
      - direction: desc
  - pop-abs-temp:
      - direction: desc
  - pop-abs-time:
      - direction: desc
---


```

**Comment by rgieseke** [comment]
One could have *one* meta YAML config file describing all Topics and Indicators.

**Comment by perrette** [comment]
let's continue the discussion on isipedia-meta

**Pull request merged**
